### ISSUE TITLE
Travis build fails

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap-docker-travis#1]
Any ideas why https://travis-ci.org/gap-system/gap-docker-travis fails ?

This seem to be Travis-related rather than broken by us:
```
W: Failed to fetch http://get.docker.io/ubuntu/dists/docker/main/binary-amd64/Packages  Undetermined Error
W: Failed to fetch http://get.docker.io/ubuntu/dists/docker/main/binary-i386/Packages  Undetermined Error
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "sudo apt-get -qqy update" failed and exited with 100 during .
Your build has been stopped.
```

**Comment by snim2** [comment]
This has happened to me sometimes on other projects, no idea why but restarting the Travis build manually fixed the problem. The `apt-get` man page says:

    apt-get returns zero on normal operation, decimal 100 on error.

so I don't think the `100` is a specific error, probably a network issue.

**Comment by alex-konovalov** [comment]
I've actually restarted it a couple of times already (yesterday and this morning) but to no avail. Let's hope that this will heal by itself.

**Comment by alex-konovalov** [comment]
I think this issue may be the same that is reported here: https://github.com/mitchellh/vagrant/issues/5748

**Comment by alex-konovalov** [comment]
I've fixed this issue in both `gap-container-travis` and `gap-docker-travis` repositories. It only required to change http to https in the URL. Now `gap-container-travis` buids again, but this one doesn't:

```
$ docker pull gapsystem/gap-docker
[info] POST /images/create?fromImage=gapsystem%2Fgap-docker&tag=
[9f52da89] +job pull(gapsystem/gap-docker, )
Pulling repository gapsystem/gap-docker
2015/06/02 20:37:20 unexpected EOF
Killed
The command "docker pull gapsystem/gap-docker" failed and exited with 1 during .
Your build has been stopped.
/home/travis/.bash_logout: line 1:  5903 Killed                  sekexe/run 'mount -t tmpfs -o size=8g tmpfs /var/lib/docker && docker -d -H tcp://0.0.0.0:2375'
```
Could it be that the Docker image is too big? Is there a verbose option in `docker pull` to see the progress?

**Comment by alex-konovalov** [comment]
I think this may be closed. We built everything for GAP 4.8.2 without problems.
